// <auto-generated />
using System;
using System.Collections.Generic;
using HealthIntake.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthIntake.Api.Migrations
{
    [DbContext(typeof(HealthIntakeDbContext))]
    partial class HealthIntakeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthIntake.Api.Domain.IntakeSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ScanSharpness")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientRequestId")
                        .IsUnique()
                        .HasFilter("\"ClientRequestId\" IS NOT NULL");

                    b.ToTable("IntakeSubmissions");
                });

            modelBuilder.Entity("HealthIntake.Api.Domain.IntakeSubmission", b =>
                {
                    b.OwnsMany("HealthIntake.Api.Domain.IntakeAnswerRecord", "Answers", b1 =>
                        {
                            b1.Property<Guid>("IntakeSubmissionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Answer")
                                .IsRequired();

                            b1.Property<string>("QuestionId")
                                .IsRequired();

                            b1.HasKey("IntakeSubmissionId", "__synthesizedOrdinal");

                            b1.ToTable("IntakeSubmissions");

                            b1
                                .ToJson("Answers")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IntakeSubmissionId");
                        });

                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
